namespace: local

resources:
  - service.yml
  - configmap.yml
  - genesis.yml
  - validator.yml
  - ingress.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: test-addresses-wasm
    files:
      - configs/keys.json
      - configs/validators.json
      - configs/cw20_base.wasmd
      - configs/cw20_ics20.wasm
