name: Docker

on:
  push:
    branches:
      - 'main'
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push persistenceCore latest
        if: github.event.push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: persistenceone/persistencecore:latest
          file: docker/persistencecore/Dockerfile

      - name: Build and push persistencecore release
        if: github.event.release
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          file: docker/persistencecore/Dockerfile


