name: Docker

on:
  push:
    branches:
      - 'master'
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: checkout repo
        uses: actions/checkout@v2

      - name: build and push docker-image date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: build and push docker-image tags
        id: gen_tags
        run: |
          echo $GITHUB_REF
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["latest","'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='["'${{ steps.date.outputs.date }}'_'$(echo ${GITHUB_SHA} | cut -c 1-5)'"]'
          fi
          echo '::set-output name=tags::'$TAGS

      - name: build and push docker-image
        if: github.event.push
        run: make DOCKER_TAG_NAME=${{ steps.gen_tags.outputs.tags }} DOCKER_IMAGE_NAME=persistenceone/persistencecore PROCESS=persistencecore docker-build-push

      - name: build and push docker-image for release
        if: github.event.release
        run: make DOCKER_TAG_NAME=${{ steps.gen_tags.outputs.tags }} DOCKER_IMAGE_NAME=persistenceone/persistencecore PROCESS=persistencecore docker-build-push

  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            exposer:
              - 'docker/exposer/**'
            core:
              - 'docker/persistencecore/**'

      - name: Set up QEMU
        if: steps.filter.outputs.exposer == 'true' || steps.filter.outputs.core == 'true'
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        if: steps.filter.outputs.exposer == 'true' || steps.filter.outputs.core == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: checkout repo
        if: steps.filter.outputs.exposer == 'true' || steps.filter.outputs.core == 'true'
        uses: actions/checkout@v2

      - name: build and push docker-image
        if: steps.filter.outputs.exposer == 'true' || steps.filter.outputs.core == 'true'
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: build and push docker-image
        if: steps.filter.outputs.exposer == 'true' || steps.filter.outputs.core == 'true'
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["latest","'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='["'${GITHUB_SHA} | cut -c1-8'_'${{ steps.date.outputs.date }}'"]'
          fi
          echo '::set-output name=tags::'$TAGS

      - name: build and push docker-image for core
        if: steps.filter.outputs.core == 'true'
        run: make DOCKER_TAG_NAME=${{ steps.gen_tags.outputs.tags }} DOCKER_IMAGE_NAME=persistenceone/persistencecore PROCESS=persistencecore docker-build-push

      - name: build and push docker-image for exposer
        if: steps.filter.outputs.exposer == 'true'
        run: make DOCKER_TAG_NAME=${{ steps.gen_tags.outputs.tags }} DOCKER_IMAGE_NAME=persistenceone/exposer PROCESS=exposer docker-build-push
