# This workflow builds, scans, adds set of tags on every push/PR to main branch
# and pushes the image to docker hub(only): https://hub.docker.com/repository/docker/persistenceone/persistencecore/
name: Docker CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - manasi/docker-ci

# NOTE: By default, default action:docker/build-push-action pushes image to Docker hub if registry is not specified
env:
  # params for docker build
  DOCKER_BUILD_ARGS: "--platform linux/$(PLATFORM) --no-cache --load"
  #Tags
  DOCKER_REPOSITORY: persistenceone/persistencecore
  RELEASE_TAG: latest
  NAME_TAG: v6.1.0
  DOCKER_FILE: docker/persistencecore/Dockerfile
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Get commit SHA in all possible cases
        id: commit-sha-short
        run: |
          if [ "$EVENT" == 'pull_request' ]
          then
            echo "::set-output name=sha::$(echo ${{github.event.pull_request.head.sha}})"
          elif [ "$EVENT" == 'workflow_run' ]
          then
            echo "::set-output name=sha::$(echo ${{github.event.workflow_run.head_sha}})"
          else
            echo "::set-output name=sha::$(echo $GITHUB_SHA)"
          fi
        env:
          EVENT: ${{ github.event_name }}
          REF: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

        # TODO: remove below if we will NOT use buildx/default build-push action for next steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # get the current date for the build & save in GITHUB_OUTPUT OR GITHUB_STATE if required
      # Testing: how to use GITHUB_OUTPUT since set-output is deprecated
      - name: Set current date to Github Output
        id: get_date
        run: echo "current_date=$(date +'%Y-%m-%d--%M-%S')" >> $GITHUB_OUTPUT

      # NOTE: docker/build-push-action@v3 uses the git context by default for building the docker images
      # So if build context is not local directory, set it specifically in context: .
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{env.DOCKER_REPOSITORY}}:${{env.NAME_TAG}},${{env.DOCKER_REPOSITORY}}:${{env.RELEASE_TAG}},
                ${{env.DOCKER_REPOSITORY}}:${{ steps.get_date.outputs.current_date }}
          file: ${{env.DOCKER_FILE}}
          platforms: linux/amd64

#      - name: Build docker image
#        run: docker build --file $DOCKER_FILE --build-arg --platform linux/$PLATFORM --no-cache --load
#            -t $DOCKER_REPOSITORY:NAME_TAG -t date:${{ steps.date.outputs.date }} -t release:$RELEASE_TAG
#
#      - name: Push Docker Image
#        run: docker push $DOCKER_REPOSITORY:NAME_TAG
