name: Docker

on:
  push:
    branches:
      - 'master'
  release:
    types: [published]


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/persistencecore

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: checkout repo
        uses: actions/checkout@v2

      - name: build docker-image
        if: github.event.push
        run: make docker-build PROCESS=persistencecore DOCKER_IMAGE_NAME=persistenceone/persistencecore DOCKER_TAG_NAME=latest

      - name: push docker-image
        if: github.event.push
        run: make docker-push IMAGE_NAME=persistenceone/persistencecore TAG_NAME=latest

      - name: build docker-image for release
        if: github.event.release
        run: make docker-build PROCESS=persistencecore DOCKER_IMAGE_NAME=persistenceone/persistencecore DOCKER_TAG_NAME=${{ steps.meta.outputs.tags }}

      - name: push docker-image for release
        if: github.event.release
        run: make docker-push IMAGE_NAME=persistenceone/persistencecore TAG_NAME=${{ steps.meta.outputs.tags }}






