# This workflow builds, scans, adds set of tags on every push/PR to main branch
# and pushes the image to docker hub: https://hub.docker.com/repository/docker/persistenceone/persistencecore/
name: Build & Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - manasi/docker-ci

#permissions:
#  contents: read
#  packages: write
#
#env:
#  # Use docker.io for Docker Hub if empty
#  REGISTRY: docker.io
#  # github.repository as <account>/<repo>
#  IMAGE_NAME: persistenceone/persistencecore

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        # confirm if we really need buildx/default build-push action for next steps
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
