name: Test


on:
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: tags 2
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/SHA/'* ]]; then
            TAGS='["user/image:latest","user/image:'${GITHUB_REF/refs\/SHA\//}'"]'
          else
            TAGS='["user/image:'${GITHUB_REF/refs\/SHA\//}'"]'
          fi
          echo '::set-output name=tags::'$TAGS
          echo $TAGS